# Use Go base image
FROM golang:1.23.4-alpine3.19

# Set working directory
WORKDIR /app

# Copy files
COPY . .
RUN go mod download

COPY . .

# Build the Go app
RUN go build -o alert_system ./cmd

# Run the app
CMD ["./alert_system"]
# CMD ["go","run", "./cmd/main.go"]