# Use Go base image
FROM golang:1.23.4-alpine3.19

# Set working directory
WORKDIR /app

# Copy files
COPY . .
RUN /log_collector/go mod download && /logging_system/go mod download

COPY . .

# Build the Go app
RUN go build -o logging_system ./logging_system/cmd && go build -o log_collector ./log_collector/cmd

# Run the app
CMD ["./logging_system","./log_collector"]